name: Detect API change

on:
  pull_request_target:
    paths:
    - 'http/**/*'

jobs:
  postReminderComment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commentBody = `:eyes: It looks like you're modifying API files. Don't forget:<br>
            - [ ] Update the SDK
            `;

            // Have we already commented on this PR?
            const opts = github.issues.listComments.endpoint.merge({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const comments = await github.paginate(opts);

            for (const comment of comments) {
              if (comment.user.login === "github-actions[bot]" && comment.body === commentBody) {
                console.log('already posted')
                return
              }
            }

            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody,
            });
